version: "3.8"

services:
    mysql:
    image: mysql:8.0
    container_name: mysql-db-testmandatory
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/database:/docker-entrypoint-initdb.d
    networks:
      - mysql_net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


  rawg-server:
    container_name: rawg-server
    build:
      context: ./rawg-server
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: mysql://root:rootpassword@mysql:3306/rawgdatabase
    networks:
      - frontend
      - backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./rawg-server:/app

  rawg-client:
    container_name: rawg-client
    build:
      context: ./rawg-client
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:5000
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./rawg-client:/app
      - /app/node_modules
    depends_on:
      - rawg-server
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  mysql_data:
